import { useState, useMemo } from "react";
import censusData from "./data/census-dates.json";
import StateDateCard from "./StateDateCard.jsx";
import { filterStates, groupByRegion, getPhaseStatus } from "./dates.utils.js";

const REGIONS = ["All", "North", "South", "East", "West", "Central", "Northeast", "Islands"];

function computeMiniStats(states) {
  let active = 0,
    upcoming = 0,
    completed = 0;
  for (const s of states) {
    const s1 = getPhaseStatus(s.phaseI.start, s.phaseI.end);
    const s2 = getPhaseStatus(s.phaseII.start, s.phaseII.end);
    if (s1 === "active" || s2 === "active") active++;
    else if (s1 === "upcoming" || s2 === "upcoming") upcoming++;
    else completed++;
  }
  return { active, upcoming, completed };
}

export default function DatesPage() {
  const [query, setQuery] = useState("");
  const [activeRegion, setActiveRegion] = useState("All");
  const [viewMode, setViewMode] = useState("grid");

  const filteredStates = useMemo(() => {
    let states = censusData.states;
    if (activeRegion !== "All") states = states.filter((s) => s.region === activeRegion);
    return filterStates(states, query);
  }, [query, activeRegion]);

  const grouped = useMemo(
    () => (viewMode === "grouped" ? groupByRegion(filteredStates) : null),
    [filteredStates, viewMode]
  );

  const stats = useMemo(() => computeMiniStats(filteredStates), [filteredStates]);
  const hasResults = filteredStates.length > 0;

  return (
    <main id="dates-page" className="page" aria-label="Census 2027 State-wise Dates">
      <div className="container">
        {/* Page header */}
        <div className="page-header animate-fade-up">
          <div className="page-title-row">
            <span style={{ fontSize: "2rem" }} aria-hidden="true">
              📅
            </span>
            <h1 className="section-title">Census 2027 Dates</h1>
          </div>
          <p className="page-desc">
            State-wise Phase I (Houselisting) and Phase II (Population Enumeration) schedule for all
            36 states &amp; UTs — queried from a structured dataset, not generated by AI.
          </p>
        </div>

        {/* Provisional disclaimer */}
        <div className="disclaimer animate-fade-up delay-100" role="alert" aria-live="polite">
          <span style={{ fontSize: "1.125rem", flexShrink: 0 }} aria-hidden="true">
            ⚠️
          </span>
          <div>
            <strong>Provisional Data:</strong> Dates are based on public announcements and subject
            to official notification. Always verify at{" "}
            <a
              href="https://censusindia.gov.in"
              target="_blank"
              rel="noopener noreferrer"
              style={{
                color: "var(--color-terracotta)",
                textDecoration: "underline",
                fontWeight: 600,
              }}
            >
              censusindia.gov.in
            </a>
            . Last updated: {censusData._meta.lastUpdated}.
          </div>
        </div>

        {/* Mini stats */}
        <div className="mini-stats animate-fade-up delay-200" style={{ margin: "1rem 0" }}>
          <div className="mini-stat">
            <span
              className="mini-stat-dot"
              style={{ background: "var(--color-sage)" }}
              aria-hidden="true"
            />
            <span className="mini-stat-count" style={{ color: "var(--color-sage)" }}>
              {stats.active}
            </span>
            <span>Active</span>
          </div>
          <div className="mini-stat">
            <span
              className="mini-stat-dot"
              style={{ background: "var(--color-terracotta)" }}
              aria-hidden="true"
            />
            <span className="mini-stat-count" style={{ color: "var(--color-terracotta)" }}>
              {stats.upcoming}
            </span>
            <span>Upcoming</span>
          </div>
          <div className="mini-stat">
            <span
              className="mini-stat-dot"
              style={{ background: "var(--color-ink-4-light)" }}
              aria-hidden="true"
            />
            <span className="mini-stat-count" style={{ color: "var(--color-ink-3-light)" }}>
              {stats.completed}
            </span>
            <span>Completed</span>
          </div>
          <div className="mini-stat">
            <span
              className="mini-stat-dot"
              style={{ background: "var(--color-dusty)" }}
              aria-hidden="true"
            />
            <span className="mini-stat-count" style={{ color: "var(--color-dusty)" }}>
              {filteredStates.length}
            </span>
            <span>Showing</span>
          </div>
        </div>

        {/* Controls row */}
        <div className="controls-row animate-fade-up delay-200">
          <div className="search-wrapper">
            <svg
              className="search-icon"
              width="16"
              height="16"
              viewBox="0 0 20 20"
              fill="none"
              aria-hidden="true"
            >
              <path
                d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
            </svg>
            <input
              id="state-search"
              type="search"
              className="input search-input"
              placeholder="Search state, UT, or region…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              aria-label="Search states and union territories"
              autoComplete="off"
            />
          </div>

          <div className="view-toggle shrink-0" role="group" aria-label="View mode">
            <button
              id="view-grid"
              className={`view-btn${viewMode === "grid" ? " active" : ""}`}
              onClick={() => setViewMode("grid")}
              aria-pressed={viewMode === "grid"}
            >
              ⊞ Grid
            </button>
            <button
              id="view-grouped"
              className={`view-btn${viewMode === "grouped" ? " active" : ""}`}
              onClick={() => setViewMode("grouped")}
              aria-pressed={viewMode === "grouped"}
            >
              ⊟ Grouped
            </button>
          </div>
        </div>

        {/* Region pills */}
        <div
          className="pills-row animate-fade-up delay-300"
          style={{ margin: "1rem 0" }}
          role="group"
          aria-label="Filter by region"
        >
          {REGIONS.map((region) => (
            <button
              key={region}
              id={`region-${region.toLowerCase()}`}
              className={`pill${activeRegion === region ? " active" : ""}`}
              onClick={() => setActiveRegion(region)}
              aria-pressed={activeRegion === region}
            >
              {region}
            </button>
          ))}
        </div>

        {/* Results count */}
        <p className="results-count" aria-live="polite" aria-atomic="true">
          {hasResults
            ? `Showing ${filteredStates.length} of ${censusData.states.length} states/UTs`
            : "No results found"}
        </p>

        {/* Cards */}
        {hasResults ? (
          viewMode === "grid" ? (
            <div className="grid-3 animate-fade-up delay-400">
              {filteredStates.map((state) => (
                <div key={state.id}>
                  <StateDateCard state={state} />
                </div>
              ))}
            </div>
          ) : (
            <div>
              {Object.entries(grouped)
                .sort()
                .map(([region, states]) => (
                  <section key={region} className="group-section" aria-label={`${region} region`}>
                    <h2 className="group-title">
                      <span className="group-title-line" aria-hidden="true" />
                      {region}
                      <span
                        style={{
                          color: "var(--color-ink-3-light)",
                          fontWeight: 400,
                          textTransform: "none",
                          letterSpacing: 0,
                          fontSize: ".78rem",
                        }}
                      >
                        ({states.length})
                      </span>
                    </h2>
                    <div className="grid-3">
                      {states.map((state) => (
                        <StateDateCard key={state.id} state={state} />
                      ))}
                    </div>
                  </section>
                ))}
            </div>
          )
        ) : (
          <div className="empty-state animate-fade-in">
            <p className="empty-icon" aria-hidden="true">
              🔍
            </p>
            <p className="empty-title">No states found</p>
            <p className="empty-desc">Try a different state name, abbreviation, or region.</p>
            <button
              className="btn btn-ghost btn-sm"
              onClick={() => {
                setQuery("");
                setActiveRegion("All");
              }}
            >
              Clear filters
            </button>
          </div>
        )}

        {/* Official CTA */}
        <div
          style={{
            textAlign: "center",
            marginTop: "4rem",
            paddingTop: "2rem",
            borderTop: "1px solid var(--color-border-light)",
          }}
          className="animate-fade-up delay-500"
        >
          <p
            style={{
              color: "var(--color-ink-3-light)",
              fontSize: "0.875rem",
              marginBottom: "0.75rem",
            }}
          >
            For the most accurate, up-to-date information
          </p>
          <a
            href="https://censusindia.gov.in"
            target="_blank"
            rel="noopener noreferrer"
            className="btn btn-primary"
            aria-label="Official Census of India website (new tab)"
          >
            Visit censusindia.gov.in <span aria-hidden="true">↗</span>
          </a>
        </div>
      </div>
    </main>
  );
}
